name: clima
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  geolocator: ^3.0.1
  http: ^0.12.0+4
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  json_annotation: ^3.0.0
  flutter_spinkit: ^3.1.0


dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^3.2.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/

  fonts:
  - family: Spartan MB
    fonts:
    - asset: fonts/SpartanMB-Black.otf
      weight: 900